<#
.SYNOPSIS
    Install or update Homesh on the Oracle standby.

.DESCRIPTION
    Everything the standby needs, from a machine that has just been created to a
    stack answering on its loopback address: Docker, the repository, the
    configuration, the build, and a check that it came up as a standby.

    It is safe to run again. A second run updates the checkout to the newest
    commit on main and rebuilds, which is how the standby is upgraded.

    Nothing about the machine is stored in the repository. The address comes
    from .local\standby-ip and the secrets from this PC's own .env, both of
    which are untracked.

.PARAMETER Tailscale
    Also join the tailnet and serve HTTPS on it, using the one-off key in
    .local\tailscale-authkey. Until this has been done the standby answers only
    on the machine itself.

.EXAMPLE
    .\tools\deploy-standby.ps1

.EXAMPLE
    .\tools\deploy-standby.ps1 -Tailscale
#>
[CmdletBinding()]
param(
    [switch]$Tailscale
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
Set-Location $repo

function Need-File([string]$path, [string]$what) {
    if (-not (Test-Path $path)) { throw "$what is missing: $path" }
    return (Get-Content $path -Raw).Trim()
}

$key     = "$repo\.local\standby_ed25519"
Need-File $key "The SSH key for the standby" | Out-Null

# OpenSSH on Windows refuses a private key that other accounts can read, and the
# refusal ("UNPROTECTED PRIVATE KEY FILE") stops the whole script. Inheritance
# off, this account only.
icacls $key /inheritance:r /grant:r "$($env:USERNAME):(R)" | Out-Null

# Keepalives, because the build is several quiet minutes on one core and
# something between here and the machine drops a connection that says nothing
# for long enough -- the second deploy died that way, exit 255, with the image
# half built and the old container still running.
$ssh = @('-i', $key, '-o', 'StrictHostKeyChecking=accept-new', '-o', 'ConnectTimeout=20',
         '-o', 'ServerAliveInterval=30', '-o', 'ServerAliveCountMax=10')

# ---- The configuration the standby runs on ----------------------------------------

$env_ = @{}
foreach ($line in Get-Content "$repo\.env") {
    if ($line -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$') { $env_[$Matches[1]] = $Matches[2] }
}

function New-Key {
    # 32 bytes, urlsafe base64 -- the shape config.py validates. The padding
    # stays: Python's urlsafe_b64decode is strict about it, and a key stripped
    # of its "=" is refused at startup with "must be urlsafe-base64".
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes).Replace('+', '-').Replace('/', '_')
}

# The standby's own name on the tailnet, derived from this PC's: same tailnet,
# different host. A passkey belongs to a hostname, so this is also the name each
# phone registers against once.
$origin = $env_['PUBLIC_ORIGIN']
if ($origin -notmatch '^https://[^.]+\.(.+)$') {
    throw "PUBLIC_ORIGIN in .env is not a tailnet address, so the standby's name cannot be derived from it."
}
$standbyHost = "homesh-standby.$($Matches[1])"

# Which way in. Over the tailnet once it has joined -- the public SSH port is
# closed after that and refuses -- and by the public address only for the very
# first install, before there is a tailnet to use.
$ErrorActionPreference = 'Continue'
& ssh @ssh -o BatchMode=yes -o ConnectTimeout=10 "ubuntu@$standbyHost" 'true' 2>$null
$onTailnet = ($LASTEXITCODE -eq 0)
$ErrorActionPreference = 'Stop'
if ($onTailnet) {
    $remote = "ubuntu@$standbyHost"
} else {
    $address = Need-File "$repo\.local\standby-ip" "The standby's public address (first install only)"
    $remote = "ubuntu@$address"
}

# Its own signing keys, deliberately not the PC's. Nothing needs them to match --
# sessions and passkeys are per-address anyway -- and a standby that cannot mint
# a token the PC would honour is one less thing that a break-in reaches.
#
# Kept across runs. They were generated afresh every time at first, which is
# harmless on a machine nobody has signed in to and, after that, signs everybody
# out on every upgrade.
$kept = @{}
$ErrorActionPreference = 'Continue'
$existing = & ssh @ssh $remote "sudo grep -E '^(MASTER_KEY|SECRET_KEY)=' /opt/homesh/.env 2>/dev/null" 2>$null
$ErrorActionPreference = 'Stop'
foreach ($line in @($existing)) {
    if ($line -match '^(MASTER_KEY|SECRET_KEY)=(.+)$') { $kept[$Matches[1]] = $Matches[2].Trim() }
}
$masterKey = if ($kept['MASTER_KEY']) { $kept['MASTER_KEY'] } else { New-Key }
$secretKey = if ($kept['SECRET_KEY']) { $kept['SECRET_KEY'] } else { New-Key }
if ($kept.Count -eq 2) { Write-Host "  Keeping the standby's own signing keys." -ForegroundColor DarkGray }

function Build-Env([string]$hostname) {
    $lines = @(
        "# Generated by tools/deploy-standby.ps1. Do not edit by hand.",
        "HOMESH_ROLE=standby",
        "PUBLIC_ORIGIN=https://$hostname",
        "RP_ID=$hostname",
        "RP_NAME=$($env_['RP_NAME'])",
        "MASTER_KEY=$masterKey",
        "SECRET_KEY=$secretKey",
        "LOG_LEVEL=$($env_['LOG_LEVEL'])",
        "MEDIA_URL_TTL_MINUTES=$($env_['MEDIA_URL_TTL_MINUTES'])",
        "",
        "# The database, which lives beside it in its own container.",
        "POSTGRES_USER=$($env_['POSTGRES_USER'])",
        "POSTGRES_PASSWORD=$($env_['POSTGRES_PASSWORD'])",
        "POSTGRES_DB=$($env_['POSTGRES_DB'])",
        "DATABASE_URL=$($env_['DATABASE_URL'])",
        "",
        "# The same bucket and the same backup key as the PC: the bucket is the",
        "# only thing the two machines share, and the key is what makes reading",
        "# it possible at all.",
        "BACKUP_KEY=$($env_['BACKUP_KEY'])",
        "OFFSITE_PROVIDER=$($env_['OFFSITE_PROVIDER'])",
        "OFFSITE_REGION=$($env_['OFFSITE_REGION'])",
        "OFFSITE_NAMESPACE=$($env_['OFFSITE_NAMESPACE'])",
        "OFFSITE_BUCKET=$($env_['OFFSITE_BUCKET'])",
        "OFFSITE_ACCESS_KEY=$($env_['OFFSITE_ACCESS_KEY'])",
        "OFFSITE_SECRET_KEY=$($env_['OFFSITE_SECRET_KEY'])",
        "",
        "# No disks here. Nothing is granted to the standby and nothing can be:",
        "# the files it can play are the ones on Drive, which it reads itself.",
        "MEDIA_ROOTS=",
        ""
    )
    # LF endings: this is read by a Linux container, and a stray carriage return
    # ends up inside a password.
    return ($lines -join "`n")
}

# ssh and scp report progress on stderr, and PowerShell 5.1 turns a native
# command's stderr into error records -- which under the stop preference this
# script starts with ends the whole run on "debconf: delaying package
# configuration". The exit code is the thing that says whether it worked.
function Send([string]$localPath, [string]$remotePath) {
    $ErrorActionPreference = 'Continue'
    & scp @ssh $localPath "${remote}:$remotePath"
    if ($LASTEXITCODE -ne 0) { throw "Could not copy $localPath to the standby." }
}

function Run([string]$command) {
    $ErrorActionPreference = 'Continue'
    & ssh @ssh $remote $command
    if ($LASTEXITCODE -ne 0) { throw "Failed on the standby: $command" }
}

$staging = Join-Path $env:TEMP "homesh-standby"
New-Item -ItemType Directory -Force -Path $staging | Out-Null
$envFile = Join-Path $staging "homesh.env"

Write-Host "Configuring the standby as $standbyHost" -ForegroundColor Cyan
[System.IO.File]::WriteAllText($envFile, (Build-Env $standbyHost))

Send $envFile "/tmp/homesh.env"
if (Test-Path "$repo\.secrets\gdrive.json") {
    Send "$repo\.secrets\gdrive.json" "/tmp/homesh-gdrive.json"
} else {
    Write-Host "  No Drive credential here, so the standby will have none." -ForegroundColor Yellow
}
Send "$repo\tools\standby-setup.sh" "/tmp/standby-setup.sh"

Write-Host "Installing. The first run builds the image and takes a while." -ForegroundColor Cyan
Run "bash /tmp/standby-setup.sh"

if ($Tailscale) {
    $authkey = Need-File "$repo\.local\tailscale-authkey" "The Tailscale key"
    $keyFile = Join-Path $staging "authkey"
    [System.IO.File]::WriteAllText($keyFile, $authkey)

    Send $keyFile "/tmp/homesh-authkey"
    Remove-Item $keyFile -Force
    Send "$repo\tools\standby-tailscale.sh" "/tmp/standby-tailscale.sh"

    Write-Host "Joining the tailnet" -ForegroundColor Cyan
    Run "bash /tmp/standby-tailscale.sh"

    # What it is actually called there, rather than what was assumed above: a
    # name already taken gets a suffix, and a passkey registered against the
    # wrong name is a sign-in that fails for reasons nobody can see.
    # Read from a file the join script wrote, rather than asked with a Python
    # one-liner: PowerShell 5.1 strips the inner quotes from a native command's
    # argument, and the first run ended on a bash syntax error right here.
    $ErrorActionPreference = 'Continue'
    $actual = "$(& ssh @ssh $remote 'cat /tmp/homesh-dnsname' 2>$null)".Trim()
    if ($actual -and $actual -ne $standbyHost) {
        Write-Host "  It joined as $actual. Rewriting its configuration to match." -ForegroundColor Yellow
        [System.IO.File]::WriteAllText($envFile, (Build-Env $actual))
        Send $envFile "/tmp/homesh.env"
        Run "sudo install -m 600 -o root -g root /tmp/homesh.env /opt/homesh/.env && sudo rm -f /tmp/homesh.env && cd /opt/homesh && sudo docker compose -f docker-compose.standby.yml up -d"
    }
}

Remove-Item $envFile -Force -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Done." -ForegroundColor Green
if (-not $Tailscale) {
    Write-Host "It answers only on the machine itself until -Tailscale has been run." -ForegroundColor DarkGray
}
